version = 1

exclude_patterns = [
  "mockup-api/**",
  "org/**"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]

[[transformers]]
name = "prettier"