<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * BlogPatchBody
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class BlogPatchBody extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "minProperties" : 1,
  "type" : "object",
  "properties" : {
    "title" : {
      "maxLength" : 100,
      "minLength" : 5,
      "type" : "string",
      "description" : "Title of the blog post.",
      "example" : "Welcome to the world of FLUG!"
    },
    "slug" : {
      "maxLength" : 150,
      "minLength" : 5,
      "type" : "string",
      "description" : "Unique slug in blogs.",
      "example" : "welcome-to-the-world-of-flug"
    },
    "shortDesc" : {
      "maxLength" : 155,
      "minLength" : 145,
      "type" : "string",
      "description" : "Short description of the blog post.",
      "example" : "A thorough introduction to the FLUG organization and what it means for you and your work with Linux in professional life..."
    },
    "image" : {
      "$ref" : "#/components/schemas/BlogPostBody_image"
    },
    "content" : {
      "maxLength" : 65535,
      "minLength" : 300,
      "type" : "string",
      "description" : "Content of the blog post in Markdown format.",
      "example" : "This blog will introduce you to the basics..."
    }
  }
}
SCHEMA;
}
