<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * BlogItem
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class BlogItem extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "uid" : {
      "type" : "integer",
      "description" : "Unique identifier for the blog."
    },
    "title" : {
      "type" : "string",
      "description" : "Title of the blog post."
    },
    "shortDesc" : {
      "type" : "string",
      "description" : "A brief description of the blog post."
    },
    "image" : {
      "$ref" : "#/components/schemas/ImageRef"
    },
    "createdAt" : {
      "type" : "string",
      "description" : "ISO 8601 representation when the blog was created.",
      "format" : "date-time"
    },
    "updatedAt" : {
      "type" : "string",
      "description" : "ISO 8601 representation when the blog was last updated.",
      "format" : "date-time",
      "nullable" : true
    }
  }
}
SCHEMA;
}
