<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * CreateEventRequest
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class CreateEventRequest extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "title" : {
      "maxLength" : 100,
      "minLength" : 5,
      "type" : "string",
      "description" : "Title of the event.",
      "example" : "FLUG event!"
    },
    "slug" : {
      "maxLength" : 150,
      "minLength" : 5,
      "type" : "string",
      "description" : "Unique slug in events.",
      "example" : "flug-event"
    },
    "shortDesc" : {
      "maxLength" : 155,
      "minLength" : 145,
      "type" : "string",
      "description" : "Short description of the event.",
      "example" : "A thorough introduction to the FLUG organization and what it means for you and your work with Linux in professional life..."
    },
    "startDateTime" : {
      "type" : "string",
      "description" : "The start date and time of the event.",
      "format" : "date-time",
      "example" : "2023-12-01T09:00:00Z"
    },
    "endDateTime" : {
      "type" : "string",
      "description" : "The end date and time of the event. Need to be later than `startDateTime`.",
      "format" : "date-time",
      "example" : "2023-12-01T11:00:00Z"
    },
    "location" : {
      "type" : "string",
      "description" : "Location where the event takes place.",
      "example" : "Willowbrook Lane 17, Welford-on-Avon, Warwickshire, CV37 8JA, United Kingdom"
    },
    "content" : {
      "maxLength" : 65535,
      "minLength" : 300,
      "type" : "string",
      "description" : "Content of the event in HTML format.",
      "example" : "This event will introduce you to the basics..."
    }
  }
}
SCHEMA;
}
