<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * Gets
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Gets extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "items" : {
      "type" : "array",
      "items" : { }
    },
    "pagination" : {
      "$ref" : "#/components/schemas/Gets_pagination"
    },
    "results" : {
      "type" : "integer"
    },
    "totalResults" : {
      "type" : "integer"
    },
    "page" : {
      "type" : "integer"
    },
    "totalPages" : {
      "type" : "integer"
    }
  },
  "example" : {
    "items" : [ "{Item 1}", "{Item 2}", "{Item 3}" ],
    "pagination" : {
      "first" : 1,
      "prev" : 1,
      "self" : 1,
      "next" : 1,
      "last" : 1
    },
    "results" : 3,
    "totalResults" : 3,
    "page" : 1,
    "totalPages" : 1
  }
}
SCHEMA;
}
