<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * UserPostBody
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class UserPostBody extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "email", "firstName" ],
  "type" : "object",
  "properties" : {
    "firstName" : {
      "maxLength" : 50,
      "minLength" : 2,
      "type" : "string",
      "description" : "First name of the user.",
      "example" : "John"
    },
    "lastName" : {
      "maxLength" : 50,
      "minLength" : 2,
      "type" : "string",
      "description" : "Last name of the user.",
      "nullable" : true,
      "example" : "Doe"
    },
    "email" : {
      "maxLength" : 100,
      "minLength" : 5,
      "type" : "string",
      "description" : "Unique email address of the user.",
      "example" : "johndoe@example.com"
    }
  }
}
SCHEMA;
}
