<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\GetResourcesPagination;

/**
 * GetResourcesPaginationTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\GetResourcesPagination
 */
class GetResourcesPaginationTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetResourcesPagination"
     */
    public function testGetResourcesPagination()
    {
        $testGetResourcesPagination = new GetResourcesPagination();
        $namespacedClassname = GetResourcesPagination::getModelsNamespace() . '\\GetResourcesPagination';
        $this->assertSame('\\' . GetResourcesPagination::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "GetResourcesPagination" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "first"
     */
    public function testPropertyFirst()
    {
        self::markTestIncomplete(
            'Test of "first" property in "GetResourcesPagination" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "prev"
     */
    public function testPropertyPrev()
    {
        self::markTestIncomplete(
            'Test of "prev" property in "GetResourcesPagination" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "current"
     */
    public function testPropertyCurrent()
    {
        self::markTestIncomplete(
            'Test of "current" property in "GetResourcesPagination" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "next"
     */
    public function testPropertyNext()
    {
        self::markTestIncomplete(
            'Test of "next" property in "GetResourcesPagination" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "last"
     */
    public function testPropertyLast()
    {
        self::markTestIncomplete(
            'Test of "last" property in "GetResourcesPagination" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = GetResourcesPagination::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

