<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\UpdateUserRequest;

/**
 * UpdateUserRequestTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\UpdateUserRequest
 */
class UpdateUserRequestTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateUserRequest"
     */
    public function testUpdateUserRequest()
    {
        $testUpdateUserRequest = new UpdateUserRequest();
        $namespacedClassname = UpdateUserRequest::getModelsNamespace() . '\\UpdateUserRequest';
        $this->assertSame('\\' . UpdateUserRequest::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "UpdateUserRequest" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "firstName"
     */
    public function testPropertyFirstName()
    {
        self::markTestIncomplete(
            'Test of "firstName" property in "UpdateUserRequest" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {
        self::markTestIncomplete(
            'Test of "lastName" property in "UpdateUserRequest" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
        self::markTestIncomplete(
            'Test of "email" property in "UpdateUserRequest" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = UpdateUserRequest::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

