<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\User;

/**
 * UserTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\User
 */
class UserTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "User"
     */
    public function testUser()
    {
        $testUser = new User();
        $namespacedClassname = User::getModelsNamespace() . '\\User';
        $this->assertSame('\\' . User::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "User" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
        self::markTestIncomplete(
            'Test of "uid" property in "User" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "firstName"
     */
    public function testPropertyFirstName()
    {
        self::markTestIncomplete(
            'Test of "firstName" property in "User" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {
        self::markTestIncomplete(
            'Test of "lastName" property in "User" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
        self::markTestIncomplete(
            'Test of "email" property in "User" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
        self::markTestIncomplete(
            'Test of "createdAt" property in "User" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "updatedAt"
     */
    public function testPropertyUpdatedAt()
    {
        self::markTestIncomplete(
            'Test of "updatedAt" property in "User" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "loggedInAt"
     */
    public function testPropertyLoggedInAt()
    {
        self::markTestIncomplete(
            'Test of "loggedInAt" property in "User" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = User::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}

