<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace OpenAPIServer\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractGetApi Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractGetApi
{
    /**
     * GET getBlog
     * Summary: Retrieve a specific blog post
     * Notes: Retrieves details of a specific blog post by ID
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param GetBlogIdParameter $id UID or SLUG of the resource to retrieve or modify
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getBlog(
        ServerRequestInterface $request,
        ResponseInterface $response,
        GetBlogIdParameter $id
    ): ResponseInterface {
        $message = "How about implementing getBlog as a GET method in OpenAPIServer\Api\GetApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getEvent
     * Summary: Retrieve a specific event
     * Notes: Retrieves details of a specific event by ID
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param GetBlogIdParameter $id UID or SLUG of the resource to retrieve or modify
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getEvent(
        ServerRequestInterface $request,
        ResponseInterface $response,
        GetBlogIdParameter $id
    ): ResponseInterface {
        $message = "How about implementing getEvent as a GET method in OpenAPIServer\Api\GetApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getImage
     * Summary: Retrieve a specific image
     * Notes: Retrieves details of a specific image by ID
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param int $uid UID of the resource to retrieve or modify
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getImage(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $uid
    ): ResponseInterface {
        $message = "How about implementing getImage as a GET method in OpenAPIServer\Api\GetApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getUser
     * Summary: Retrieve a specific user
     * Notes: Retrieves details of a specific user by ID
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param int $uid UID of the resource to retrieve or modify
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getUser(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $uid
    ): ResponseInterface {
        $message = "How about implementing getUser as a GET method in OpenAPIServer\Api\GetApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
