<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace OpenAPIServer\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractDeleteApi Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractDeleteApi
{
    /**
     * DELETE deleteBlog
     * Summary: Delete a blog post
     * Notes: Removes a specific blog post from the system by ID
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param int $uid UID of the resource to retrieve or modify
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteBlog(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $uid
    ): ResponseInterface {
        $message = "How about implementing deleteBlog as a DELETE method in OpenAPIServer\Api\DeleteApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * DELETE deleteEvent
     * Summary: Delete a event
     * Notes: Removes a specific event from the system by ID
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param int $uid UID of the resource to retrieve or modify
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteEvent(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $uid
    ): ResponseInterface {
        $message = "How about implementing deleteEvent as a DELETE method in OpenAPIServer\Api\DeleteApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * DELETE deleteImage
     * Summary: Delete a image
     * Notes: Removes a specific image from the system by ID
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param int $uid UID of the resource to retrieve or modify
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteImage(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $uid
    ): ResponseInterface {
        $message = "How about implementing deleteImage as a DELETE method in OpenAPIServer\Api\DeleteApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * DELETE deleteUser
     * Summary: Delete a user
     * Notes: Removes a specific user from the system by ID
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param int $uid UID of the resource to retrieve or modify
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteUser(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $uid
    ): ResponseInterface {
        $message = "How about implementing deleteUser as a DELETE method in OpenAPIServer\Api\DeleteApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
