<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\CreateApi;

/**
 * CreateApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\CreateApi
 */
class CreateApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createBlog
     *
     * Create a new blog post.
     *
     * @covers ::createBlog
     */
    public function testCreateBlog()
    {
        self::markTestIncomplete(
            'Test of "createBlog" method has not been implemented yet.'
        );
    }

    /**
     * Test case for createEvent
     *
     * Create a new event.
     *
     * @covers ::createEvent
     */
    public function testCreateEvent()
    {
        self::markTestIncomplete(
            'Test of "createEvent" method has not been implemented yet.'
        );
    }

    /**
     * Test case for createImage
     *
     * Create a new image.
     *
     * @covers ::createImage
     */
    public function testCreateImage()
    {
        self::markTestIncomplete(
            'Test of "createImage" method has not been implemented yet.'
        );
    }

    /**
     * Test case for createUser
     *
     * Create a new user.
     *
     * @covers ::createUser
     */
    public function testCreateUser()
    {
        self::markTestIncomplete(
            'Test of "createUser" method has not been implemented yet.'
        );
    }
}
