<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\DeleteApi;

/**
 * DeleteApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\DeleteApi
 */
class DeleteApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteBlog
     *
     * Delete a blog post.
     *
     * @covers ::deleteBlog
     */
    public function testDeleteBlog()
    {
        self::markTestIncomplete(
            'Test of "deleteBlog" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteEvent
     *
     * Delete a event.
     *
     * @covers ::deleteEvent
     */
    public function testDeleteEvent()
    {
        self::markTestIncomplete(
            'Test of "deleteEvent" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteImage
     *
     * Delete a image.
     *
     * @covers ::deleteImage
     */
    public function testDeleteImage()
    {
        self::markTestIncomplete(
            'Test of "deleteImage" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteUser
     *
     * Delete a user.
     *
     * @covers ::deleteUser
     */
    public function testDeleteUser()
    {
        self::markTestIncomplete(
            'Test of "deleteUser" method has not been implemented yet.'
        );
    }
}
