<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\GetApi;

/**
 * GetApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\GetApi
 */
class GetApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getBlog
     *
     * Retrieve a specific blog post.
     *
     * @covers ::getBlog
     */
    public function testGetBlog()
    {
        self::markTestIncomplete(
            'Test of "getBlog" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getEvent
     *
     * Retrieve a specific event.
     *
     * @covers ::getEvent
     */
    public function testGetEvent()
    {
        self::markTestIncomplete(
            'Test of "getEvent" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getImage
     *
     * Retrieve a specific image.
     *
     * @covers ::getImage
     */
    public function testGetImage()
    {
        self::markTestIncomplete(
            'Test of "getImage" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getUser
     *
     * Retrieve a specific user.
     *
     * @covers ::getUser
     */
    public function testGetUser()
    {
        self::markTestIncomplete(
            'Test of "getUser" method has not been implemented yet.'
        );
    }
}
