<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\GetsApi;

/**
 * GetsApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\GetsApi
 */
class GetsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getBlogs
     *
     * Retrieve list of blog posts.
     *
     * @covers ::getBlogs
     */
    public function testGetBlogs()
    {
        self::markTestIncomplete(
            'Test of "getBlogs" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getEvents
     *
     * Retrieve list of events.
     *
     * @covers ::getEvents
     */
    public function testGetEvents()
    {
        self::markTestIncomplete(
            'Test of "getEvents" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getImages
     *
     * Retrieve list of images.
     *
     * @covers ::getImages
     */
    public function testGetImages()
    {
        self::markTestIncomplete(
            'Test of "getImages" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getUsers
     *
     * Retrieve list of users.
     *
     * @covers ::getUsers
     */
    public function testGetUsers()
    {
        self::markTestIncomplete(
            'Test of "getUsers" method has not been implemented yet.'
        );
    }
}
