<?php

/**
 * FLUG Service API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A service API for the Fyns Linux User Group website
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\UpdateApi;

/**
 * UpdateApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\UpdateApi
 */
class UpdateApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for updateBlog
     *
     * Update blog post details.
     *
     * @covers ::updateBlog
     */
    public function testUpdateBlog()
    {
        self::markTestIncomplete(
            'Test of "updateBlog" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateEvent
     *
     * Update event details.
     *
     * @covers ::updateEvent
     */
    public function testUpdateEvent()
    {
        self::markTestIncomplete(
            'Test of "updateEvent" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateImage
     *
     * Update image details.
     *
     * @covers ::updateImage
     */
    public function testUpdateImage()
    {
        self::markTestIncomplete(
            'Test of "updateImage" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateUser
     *
     * Update user details.
     *
     * @covers ::updateUser
     */
    public function testUpdateUser()
    {
        self::markTestIncomplete(
            'Test of "updateUser" method has not been implemented yet.'
        );
    }
}
